### ISSUE TITLE
[Flat config] Cannot use `browser` or `recommended`

### ISSUE THREAD

**Issue by boris-petrov** [github/eslint-plugin-github#576]
Congrats on the new release with flat-config support!

Trying to use `github.getFlatConfigs().browser` leads to the following error though:

```
TypeError: context.getScope is not a function
Occurred while linting /home/boris/project/file.ts:61
Rule: "github/async-preventdefault"
    at CallExpression (/home/boris/project/node_modules/.pnpm/eslint-plugin-github@5.1.0_@types+eslint@9.6.1_@typescript-eslint+parser@8.15.0_eslint@9.15.0_pya6p6ja3qpsrjsqqan2f6352q/node_modules/eslint-plugin-github/lib/rules/async-preventdefault.js:20:33)
    at ruleErrorHandler (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1098:48)
    at /home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/node-event-generator.js:337:14)
    at runRules (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1142:40)
    at #flatVerifyWithoutProcessors (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/linter/linter.js:1911:31)
```

While using `github.getFlatConfigs().recommended` leads to:

```
Error: Key "rules": Key "filenamesPlugin/match-regex":
        Value ["^[a-z0-9-]+(.[a-z0-9-]+)?$"] should NOT have more than 0 items.

    at RuleValidator.validate (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/config/rule-validator.js:170:27)
    at new Config (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/config/config.js:228:27)
    at [finalizeConfig] (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/config/flat-config-array.js:216:16)
    at FlatConfigArray.getConfigWithStatus (/home/boris/project/node_modules/.pnpm/@eslint+config-array@0.19.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1178:55)
    at FlatConfigArray.getConfig (/home/boris/project/node_modules/.pnpm/@eslint+config-array@0.19.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1196:15)
    at entryFilter (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/eslint/eslint-helpers.js:282:40)
    at async NodeHfs.<anonymous> (file:///home/boris/project/node_modules/.pnpm/@humanfs+core@0.19.1/node_modules/@humanfs/core/src/hfs.js:574:24)
    at async NodeHfs.<anonymous> (file:///home/boris/project/node_modules/.pnpm/@humanfs+core@0.19.1/node_modules/@humanfs/core/src/hfs.js:604:6)
    at async NodeHfs.walk (file:///home/boris/project/node_modules/.pnpm/@humanfs+core@0.19.1/node_modules/@humanfs/core/src/hfs.js:614:3)
    at async globSearch (/home/boris/project/node_modules/.pnpm/eslint@9.15.0/node_modules/eslint/lib/eslint/eslint-helpers.js:323:26)
```

`...github.getFlatConfigs().typescript` works fine.

**Comment by boris-petrov** [comment]
Works like a charm! Thank you!
